export const LOGGED_IN = 'auth/LOGGED_IN';
export const LOGGED_OUT = 'auth/LOGGED_OUT';
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const FETCHED_DATA = 'FETCHED_DATA';
export const FETCHEDING_DATA = 'FETCHEDING_DATA';
export const FETCH_DATA_FAILED = 'FETCH_DATA_FAILED';

export const SENT_FOLLOW_REQUEST = 'SENT_FOLLOW_REQUEST';
export const SENDING_FOLLOW_REQUEST = 'SENDING_FOLLOW_REQUEST';
export const FAILED_FOLLOW_REQUEST = 'FAILED_FOLLOW_REQUEST';

export const FETCHED_FEED = "FETCHED_FEED"
export const FETCH_FEED_FAILD = "FETCH_FEED_FAILD"
export const FETCHING_FEED = "FETCHING_FEED"


export const FETCHING_COMMENTS = 'FETCHING_COMMENTS'
export const FETCHED_COMMENTS = 'FETCHED_COMMENTS'
export const FETCHED_COMMENTS_FAILED = 'FETCHED_COMMENTS_FAILED'


export const FETCHING_FOLOWING_ACCOUNTS = 'FETCHING_FOLOWING_ACCOUNTS'
export const FETCHED_FOLOWING_ACCOUNTS = 'FETCHED_FOLOWING_ACCOUNTS'
export const FETCHED_FOLOWING_ACCOUNTS_FAILED = 'FETCHED_FOLOWING_ACCOUNTS_FAILED'

export const FETCHING_GROUPS = 'FETCHING_GROUPS'
export const FETCHED_GROUPS = 'FETCHED_GROUPS'
export const FAILED_FETCHED_GROUPS = 'FAILED_FETCHED_GROUPS'


export const FETCHING_GROUP_ACCESSORIES = 'FETCHING_GROUP_ACCESSORIES'
export const GET_GROUP_ACCESSORIES = 'GET_GROUP_ACCESSORIES'
export const GET_GROUP_ACCESSORIES_FAILED = 'GET_GROUP_ACCESSORIES_FAILED'

export const FETCH_ACCESSORIES = 'FETCH_ACCESSORIES'


export const ADDING_ANNOUNCEMENT = 'ADDING_ANNOUNCEMENT'
export const ADDED_ANNOUNCEMENT = 'ADDED_ANNOUNCEMENT'

export const FETCHING_ANNOUNCEMENT = 'FETCHING_ANNOUNCEMENT'
export const FETCHED_ANNOUNCEMENT = 'FETCHED_ANNOUNCEMENT'
export const FETCHED_ANNOUNCEMENT_FAILED = 'FETCHED_ANNOUNCEMENT_FAILED'